export const levels = [
  { value: "JUEC1", title: "统考初中一" },
  { value: "JUEC2", title: "统考初中二" },
  { value: "JUEC3", title: "统考初中三" },
  { value: "SUEC1", title: "统考高中一" },
  { value: "SUEC2", title: "统考高中二" },
  { value: "SUEC3", title: "统考高中三" },
  { value: "FORM1", title: "Form 1（政府中学）" },
  { value: "FORM2", title: "Form 2（政府中学）" },
  { value: "FORM3", title: "Form 3（政府中学）" },
  { value: "PT3"  , title: "PT3"  },
  { value: "FORM4", title: "Form 4（政府中学）" },
  { value: "FORM5", title: "Form 5（政府中学）" },
  { value: "SPM"  , title: "SPM"  },
  { value: "FORM6", title: "Form 6（政府中学）" },
  { value: "STPM" , title: "STPM"  },
  { value: "IGCSE", title: "IGCSE" },
  { value: "ALEVEL", title: "GCE A-levels" },
  { value: "AUSMAT", title: "AUSMAT"},
  { value: "IB"    , title: "International Baccalaureate" },
  { value: "UNI"   , title: "大学" },
]